---
- name: Install Java
  hosts: jenkins_slave
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present

- name: Download and install Jenkins JNLP Agent
  hosts: jenkins_slave
  become: yes
  vars:
    jenkins_url: "http://your-jenkins-master-url/" # here
    jenkins_secret: "your-jenkins-secret" # here
    jenkins_agent_name: "your-agent-name" # here
  tasks:
    - name: Create Jenkins agent directory
      file:
        path: "/opt/jenkins"
        state: directory

    - name: Download Jenkins agent JAR
      get_url:
        url: "{{ jenkins_url }}/jnlpJars/agent.jar"
        dest: "/opt/jenkins/agent.jar"

    - name: Create Jenkins agent service file
      template:
        src: "jenkins-agent.service.j2"
        dest: "/etc/systemd/system/jenkins-agent.service"
      notify:
        - Reload systemd

    - name: Start Jenkins agent service
      ansible.builtin.service:
        name: jenkins-agent
        state: started
        enabled: yes

  handlers:
    - name: Reload systemd
      ansible.builtin.command: "systemctl daemon-reload"
      become: yes